# Default values for samba.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: samnco/samba
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: samba
  type: ClusterIP
  externalNMBPort137: 137
  internalNMBPort137: 137
  externalNMBPort138: 138
  internalNMBPort138: 138
  externalSMBPort139: 139
  internalSMBPort139: 139
  externalSMBPort445: 445
  internalSMBPort445: 445

resources: 
  requests:
   cpu: 100m
   memory: 128Mi
  limits:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

hostNetwork: false

persistence:
  # This setup overrides persistence and mounts a hostPath. Use the host path 
  # as the value
  hostPath: false

  ## This volume persists generated configuration files, keys, and certs.
  ##
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  size: 1Gi
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  ## This volume is used to store git data and other project files.
  ## ref: https://docs.gitlab.com/omnibus/settings/configuration.html#storing-git-data-in-an-alternative-directory
  ##

