# What Benchmarks do we want to run? 

benchmarks: 
- name: pts/foo
  completions: 3 
  parallelism: 1
  image: samnco/pts:7.4.0-cuda
  gpuType: nvidia
- name: pts/bar
  completions: 2 
  parallelism: 2
  image: samnco/pts:7.4.0-nocuda
  gpuType: cpu

resources:
  manage: true
  requests:
    cpu: 4000m
    memory: 8Gi
  limits:
    cpu: 4000m
    memory: 12Gi

nodeSelector: {}

persistence:
  # This setup overrides persistence and mounts a hostPath. Use the host path 
  # as the value
  hostPath: false

  ## This volume persists generated configuration files, keys, and certs.
  ##
  enabled: true

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: 

config: 
  <?xml version="1.0"?>
  <!--Phoronix Test Suite v7.4.0-->
  <?xml-stylesheet type="text/xsl" href="xsl/pts-user-config-viewer.xsl"?>
  <PhoronixTestSuite>
    <Options>
      <OpenBenchmarking>
        <AnonymousUsageReporting>TRUE</AnonymousUsageReporting>
        <IndexCacheTTL>3</IndexCacheTTL>
        <AlwaysUploadSystemLogs>FALSE</AlwaysUploadSystemLogs>
      </OpenBenchmarking>
      <General>
        <DefaultBrowser></DefaultBrowser>
        <UsePhodeviCache>TRUE</UsePhodeviCache>
        <DefaultDisplayMode>DEFAULT</DefaultDisplayMode>
        <PhoromaticServers></PhoromaticServers>
        <FullOutput>FALSE</FullOutput>
      </General>
      <Modules>
        <LoadModules>toggle_screensaver, update_checker, perf_tips, ob_auto_compare</LoadModules>
      </Modules>
      <Installation>
        <RemoveDownloadFiles>FALSE</RemoveDownloadFiles>
        <SearchMediaForCache>TRUE</SearchMediaForCache>
        <SymLinkFilesFromCache>FALSE</SymLinkFilesFromCache>
        <PromptForDownloadMirror>FALSE</PromptForDownloadMirror>
        <EnvironmentDirectory>~/.phoronix-test-suite/installed-tests/</EnvironmentDirectory>
        <CacheDirectory>~/.phoronix-test-suite/download-cache/</CacheDirectory>
      </Installation>
      <Testing>
        <SaveSystemLogs>TRUE</SaveSystemLogs>
        <SaveInstallationLogs>FALSE</SaveInstallationLogs>
        <SaveTestLogs>FALSE</SaveTestLogs>
        <RemoveTestInstallOnCompletion></RemoveTestInstallOnCompletion>
        <ResultsDirectory>~/.phoronix-test-suite/test-results/</ResultsDirectory>
        <AlwaysUploadResultsToOpenBenchmarking>FALSE</AlwaysUploadResultsToOpenBenchmarking>
        <AutoSortRunQueue>TRUE</AutoSortRunQueue>
      </Testing>
      <TestResultValidation>
        <DynamicRunCount>TRUE</DynamicRunCount>
        <LimitDynamicToTestLength>20</LimitDynamicToTestLength>
        <StandardDeviationThreshold>3.50</StandardDeviationThreshold>
        <ExportResultsTo></ExportResultsTo>
        <MinimalTestTime>3</MinimalTestTime>
      </TestResultValidation>
      <BatchMode>
        <SaveResults>TRUE</SaveResults>
        <OpenBrowser>FALSE</OpenBrowser>
        <UploadResults>FALSE</UploadResults>
        <PromptForTestIdentifier>FALSE</PromptForTestIdentifier>
        <PromptForTestDescription>FALSE</PromptForTestDescription>
        <PromptSaveName>FALSE</PromptSaveName>
        <RunAllTestCombinations>TRUE</RunAllTestCombinations>
        <Configured>TRUE</Configured>
      </BatchMode>
      <Networking>
        <NoInternetCommunication>FALSE</NoInternetCommunication>
        <NoNetworkCommunication>FALSE</NoNetworkCommunication>
        <Timeout>20</Timeout>
        <ProxyAddress></ProxyAddress>
        <ProxyPort></ProxyPort>
        <ProxyUser></ProxyUser>
        <ProxyPassword></ProxyPassword>
      </Networking>
      <Server>
        <RemoteAccessPort>8080</RemoteAccessPort>
        <Password></Password>
        <WebSocketPort>8081</WebSocketPort>
        <AdvertiseServiceZeroConf>FALSE</AdvertiseServiceZeroConf>
        <PhoromaticStorage>~/.phoronix-test-suite/phoromatic/</PhoromaticStorage>
      </Server>
    </Options>
  </PhoronixTestSuite>
    

